### ISSUE TITLE
megacmd error

### ISSUE THREAD

**Issue by nmartinho** [t3rm1n4l/megacmd#18]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x10dc0]

goroutine 1 [running]:
main.main()
        /root/megacmd/main.go:52 +0x1c0

goroutine 2 [syscall]:
created by runtime.main
        /build/buildd/golang-1/src/pkg/runtime/proc.c:221

goroutine 3 [syscall]:
created by os/signal.init·1
        /usr/lib/go/src/pkg/os/signal/signal_unix.go:26 +0x44

**Comment by alvgarci** [comment]
Same issue here (OSX 10.10.2), just trying to list some files... any clue?

**Comment by alvgarci** [comment]
(of course last megacmd code)
