### ISSUE TITLE
Error when run megacmd

### ISSUE THREAD

**Issue by kfiasche** [t3rm1n4l/megacmd#66]
i have make this procedure step - by -step

1- yum install go
2- mkdir mega
3- cd mega
4- git clone https://github.com/t3rm1n4l/megacmd.git 
5- cd megacmd
6- export MEGA_USER=<my_username>
7- export MEGA_PASSWD=<my_pass>
8- make
9- make test

i receive this error

go get github.com/t3rm1n4l/go-mega
go get github.com/t3rm1n4l/megacmd/client
go get github.com/t3rm1n4l/go-humanize
go build -o megacmd
./tests/run_tests.sh megacmd
Setting up test env
#### EXECUTING TEST t_delete.sh ####

Executing run ../megacmd -conf=t.json -verbose=0 mkdir mega:/testing/dir1/dir2
./t_delete.sh:7 FAIL: Executing failed
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x804a9f9]

goroutine 16 [running]:
runtime.panic(0x82684c0, 0x83cbe93)
        /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xe9
main.main()
        /home/mega/megacmd/main.go:52 +0x1df9

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
        /usr/lib/golang/src/pkg/runtime/mheap.c:507
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
        /usr/lib/golang/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
        /usr/lib/golang/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
os/signal.loop()
        /usr/lib/golang/src/pkg/os/signal/signal_unix.go:19
created by os/signal.initÂ·1
        /usr/lib/golang/src/pkg/os/signal/signal_unix.go:27 +0x37
make: *** [test] Error 1

**Comment by Orbixx** [comment]
I get the same when trying to execute anything under megacmd.
