### ISSUE TITLE
Not working in Ubuntu 17.10

### ISSUE THREAD

**Issue by lf-araujo** [t3rm1n4l/megacmd#94]
I understand this code is unsupported, could anyone confirm that it stops working in latest Ubuntu? I copied the amd64 binary (which worked well in a previous installation), but now it throws me:

```
panic: crypto/cipher: input not full blocks

goroutine 1 [running]:
crypto/cipher.(*cbcDecrypter).CryptBlocks(0xc42095b310, 0xc420851840, 0x3c, 0x3c, 0xc4207b1d10, 0x2d, 0x2d)
	/opt/go/go1.9/src/crypto/cipher/cbc.go:114 +0x498
github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega.decryptAttr(0xc420a3ccd8, 0x10, 0x40, 0xc420851800, 0x3c, 0x40, 0x10, 0x12, 0x0, 0x0)
	/home/ncw/go/src/github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega/utils.go:287 +0x1f7
github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega.(*Mega).addFSNode(0xc4200b82c0, 0xc4202b97b0, 0x8, 0xc4202b97b8, 0x8, 0xc4202b97e0, 0xb, 0x1, 0xc42033a280, 0x3c, ...)
	/home/ncw/go/src/github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega/mega.go:558 +0x4be
github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega.(*Mega).getFileSystem(0xc4200b82c0, 0x0, 0x0)
	/home/ncw/go/src/github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega/mega.go:663 +0x391
github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega.(*Mega).Login(0xc4200b82c0, 0xc42008a200, 0x16, 0xc4200885c0, 0x10, 0xc4200538f8, 0x630c66)
	/home/ncw/go/src/github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega/mega.go:473 +0x50b
github.com/t3rm1n4l/megacmd/client.(*MegaClient).Login(0xc42007cca0, 0xc42007cca0, 0x0)
	/home/ncw/go/src/github.com/t3rm1n4l/megacmd/client/client.go:139 +0x56
main.main()
	/home/ncw/go/src/github.com/t3rm1n4l/megacmd/main.go:128 +0x4c5

```

- Does golang needs to be installed for these binaries to work? What am I doing wrong?

**Comment by ncw** [comment]
Can you make a reproduce for the problem please?  Something I can run to get that error and I'll have a go at fixing it.

Thanks

**Comment by lf-araujo** [comment]
That is the problem, this is the sole machine I have Ubuntu installed in... Its Ubuntu 17.10, running on BTRFS... 

Perhaps you can leave this issue opened for a few days to see if someone else is affected.

Thank you for answering.

**Comment by ncw** [comment]
What was the command line you ran?

The code should work fine on Ubuntu.

**Comment by lf-araujo** [comment]
megacmd list mega:/luis-desktop

megacmd list mega:/

Both give the same error.

**Comment by lf-araujo** [comment]
Came back to this problem, I am almost sure this is related to btrfs. This binary works in all my machines, except the sole that runs in btrfs...
